### ISSUE TITLE
Not compatible with Rails 3.0.4

### ISSUE THREAD

**Issue by aubergene** [DBA/swf_file#6]
Create a new rails project, add gem 'swf_file' to the Gemfile, bundle, rails s

.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/json/common.rb:27:in `remove_const': constant JSON::Parser not defined (NameError)

**Comment by DBA** [comment]
Not exactly sure why this gem would not work with rails 3.0.4. It's something I will have to test. However, could you try using v1.1.0.rc.2

gem 'swf_file', '1.1.0.rc.2'

Thanks
